---
resources:
  - name: concourse-test-repo
    type: git
    source:
      uri: https://github.com/nrgoncalves/concourse-test
      branch: master

jobs:
  - name: job-test-concourse
    public: true
    plan:
      - get: concourse-test-repo
      - task: run-tests
        file: concourse-test-repo/tasks/run-tests.yml
