---
platform: linux

image_resource:
  type: docker-image
  source: { repository: python }

inputs:
  - name: concourse-test-repo

run:
  path: /bin/sh
  args:
    - -c
    - |
      pip install pytest
      pytest concourse-test-repo/test_mymodule.py
